// <auto-generated />
namespace OSL.Forum.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MaxLengthofName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MaxLengthofName));
        
        string IMigrationMetadata.Id
        {
            get { return "202203160358233_MaxLengthofName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
