// <auto-generated />
namespace OSL.Forum.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class StatusInTopicTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StatusInTopicTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202204090655346_StatusInTopicTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
